/**
 * SSVI calibration (lib/quant/calibrate.ts): quote selection, exact recovery of known smiles,
 * behaviour under quote noise, the arbitrage-free boundary, and degenerate inputs.
 */

import { test, expect } from '@playwright/test';
import type { LiveChainOption } from '../lib/market/marketData';
import { calibrateSmile, MIN_QUOTES, otmQuotes, yearsToExpiry } from '../lib/quant/calibrate';
import type { SmileQuote } from '../lib/quant/calibrate';
import { mulberry32 } from '../lib/quant/rng';
import type { Market, Smile } from '../lib/quant/types';
import { legSigma, validSmile } from '../lib/quant/volSurface';

/** Quotes generated by the app's own smile at strikes from 75% to 120% of the forward. */
function quotesFrom(m: Market, T: number, n = 25, noise?: () => number): SmileQuote[] {
  const F = m.S * Math.exp((m.r - m.q) * T);
  return Array.from({ length: n }, (_, i) => {
    const K = F * (0.75 + (0.45 * i) / (n - 1));
    return { K, iv: legSigma(m, K, T) + (noise ? noise() : 0), call: K >= F };
  });
}

test.describe('SSVI calibration', () => {
  test('recovers known smiles exactly from noiseless quotes', () => {
    const u = mulberry32(31);
    const bad: string[] = [];
    for (let i = 0; i < 25; i++) {
      const rho = -0.9 + 1.5 * u(), gamma = 0.45;
      const smile: Smile = { rho, eta: 0.1 + (2 / (1 + Math.abs(rho)) - 0.15) * u(), gamma };
      const m: Market = { S: 50 + 900 * u(), sigma: 0.08 + 0.6 * u(), r: 0.05 * u(), q: 0.03 * u(), smile };
      const T = 7 / 365 + 1.5 * u();
      const cal = calibrateSmile(quotesFrom(m, T), m.S, m.r, m.q, T, gamma)!;
      const ctx = JSON.stringify({ m, T, fit: { sigma: cal.sigma, smile: cal.smile, rmse: cal.rmseVolPts } });
      if (!(cal.rmseVolPts < 1e-3)) bad.push(`rmse ${cal.rmseVolPts} ${ctx}`);
      if (!(Math.abs(cal.sigma - m.sigma) < 1e-4)) bad.push(`sigma ${ctx}`);
      if (!(Math.abs(cal.smile.rho - rho) < 2e-3)) bad.push(`rho ${ctx}`);
      if (!(Math.abs(cal.smile.eta - smile.eta) < 2e-3)) bad.push(`eta ${ctx}`);
      if (!validSmile(cal.smile)) bad.push(`invalid ${ctx}`);
    }
    expect(bad.slice(0, 5)).toEqual([]);
  });

  test('with half a vol point of quote noise, the fit error matches the noise and the ATM level holds', () => {
    const u = mulberry32(32);
    const m: Market = { S: 756.48, sigma: 0.15, r: 0.045, q: 0.012, smile: { rho: -0.7, eta: 1.1, gamma: 0.45 } };
    const T = 32 / 365;
    const noise = () => (u() - 0.5) * 0.01;   // uniform ±0.5 vol pt → RMS ≈ 0.29 vol pt
    const cal = calibrateSmile(quotesFrom(m, T, 60, noise), m.S, m.r, m.q, T)!;
    expect(cal.rmseVolPts).toBeGreaterThan(0.15);
    expect(cal.rmseVolPts).toBeLessThan(0.35);
    expect(Math.abs(cal.sigma - m.sigma)).toBeLessThan(0.003);
    expect(cal.smile.rho).toBeLessThan(-0.5);
    expect(cal.atLimit).toBe(false);
  });

  test('a smile steeper than the arbitrage-free region is fitted on its boundary and flagged', () => {
    const T = 0.25, S = 100;
    // wings far steeper than any arbitrage-free SSVI slice: 20 vol points per 10% of moneyness
    const quotes = Array.from({ length: 21 }, (_, i) => {
      const K = 70 + 3 * i, k = Math.log(K / S);
      return { K, iv: 0.2 + 2 * Math.abs(k), call: K >= S };
    });
    const cal = calibrateSmile(quotes, S, 0, 0, T)!;
    expect(validSmile(cal.smile)).toBe(true);
    expect(cal.atLimit).toBe(true);
    expect(cal.rmseVolPts).toBeGreaterThan(0.5);
  });

  test('inside the region γ only re-expresses the slice; for steep short-dated smiles a larger γ reaches further', () => {
    const T = 0.1;
    // a mild smile: both fits are interior and give the same volatilities
    const mild: Market = { S: 200, sigma: 0.3, r: 0.02, q: 0, smile: { rho: -0.35, eta: 0.5, gamma: 0.4 } };
    const a = calibrateSmile(quotesFrom(mild, T), mild.S, mild.r, mild.q, T, 0.4)!;
    const b = calibrateSmile(quotesFrom(mild, T), mild.S, mild.r, mild.q, T, 0.25)!;
    expect(a.atLimit || b.atLimit).toBe(false);
    for (let i = 0; i < a.points.length; i++) expect(Math.abs(a.points[i].ivModel - b.points[i].ivModel)).toBeLessThan(2e-5);
    expect(b.smile.gamma).toBe(0.25);
    // a steep one: φ = η·θ^−γ·(1+θ)^(γ−1) with η capped, so at small θ a small γ cannot reach it
    const steep: Market = { ...mild, smile: { rho: -0.35, eta: 1.2, gamma: 0.4 } };
    const low = calibrateSmile(quotesFrom(steep, T), steep.S, steep.r, steep.q, T, 0.25)!;
    const high = calibrateSmile(quotesFrom(steep, T), steep.S, steep.r, steep.q, T, 0.5)!;
    expect(low.atLimit).toBe(true);
    expect(high.atLimit).toBe(false);
    expect(high.rmseVolPts).toBeLessThan(low.rmseVolPts);
  });

  test('too few quotes or no time to expiry gives no calibration', () => {
    const m: Market = { S: 100, sigma: 0.2, r: 0, q: 0, smile: { rho: -0.5, eta: 1, gamma: 0.45 } };
    expect(calibrateSmile(quotesFrom(m, 0.1, MIN_QUOTES - 1), 100, 0, 0, 0.1)).toBeNull();
    expect(calibrateSmile(quotesFrom(m, 0.1), 100, 0, 0, 0)).toBeNull();
    expect(calibrateSmile([], 100, 0, 0, 0.1)).toBeNull();
  });

  test('quote selection: out of the money, a usable IV and a live quote, one per strike', () => {
    const o = (type: 'call' | 'put', strike: number, iv: number | undefined, bid = 1, last = 1): LiveChainOption =>
      ({ symbol: `${type}${strike}`, type, strike, bid, ask: bid + 0.1, last, openInterest: 10, iv });
    const chain = [
      o('put', 90, 0.25), o('call', 90, 0.21),            // below the forward: the put
      o('put', 110, 0.19), o('call', 110, 0.17),          // above: the call
      o('call', 120, undefined), o('call', 125, 0),       // no usable IV
      o('put', 80, 0.3, 0, 0),                            // no quote
      o('call', 130, 0.9),                                // far outside the ATM band
      o('put', 70, 0.34, 0, 0.05),                        // last trade only: kept
    ];
    expect(otmQuotes(chain, 100, 0.2)).toEqual([
      { K: 70, iv: 0.34, call: false }, { K: 90, iv: 0.25, call: false }, { K: 110, iv: 0.17, call: true },
    ]);
    expect(otmQuotes(chain, 100).map(q => q.K)).toEqual([70, 90, 110, 130]);   // without an ATM band
  });

  test('years to expiry counts to 4 pm New York and never less than a day', () => {
    const now = Date.parse('2026-09-14T15:00:00Z');
    expect(yearsToExpiry('2026-10-16', now)).toBeCloseTo(32 / 365, 12);
    expect(yearsToExpiry('2026-09-14', now)).toBeCloseTo(1 / 365, 12);
    expect(yearsToExpiry('2026-09-10', now)).toBeCloseTo(1 / 365, 12);
  });
});
