/**
 * SSVI calibration (lib/quant/calibrate.ts): quote selection, exact recovery of known smiles,
 * behaviour under quote noise, the arbitrage-free boundary, and degenerate inputs.
 */

import { test, expect } from '@playwright/test';
import type { LiveChainOption } from '../lib/market/marketData';
import { atmReferenceIv, calibrateSmile, calibrateSurface, MIN_QUOTES, otmQuotes, yearsToExpiry } from '../lib/quant/calibrate';
import type { SmileQuote, SurfaceSliceInput } from '../lib/quant/calibrate';
import { loadSurfaceSlices, pickSurfaceExpiries } from '../lib/market/surfaceData';
import { runTask } from '../lib/compute/tasks';
import { bsPrice } from '../lib/quant/blackScholes';
import { mulberry32 } from '../lib/quant/rng';
import type { Market, Smile } from '../lib/quant/types';
import { atmVariance, atmVol, fittedTerm, legSigma, validSmile, validTerm } from '../lib/quant/volSurface';

/** Quotes generated by the app's own smile at strikes from 75% to 120% of the forward. */
function quotesFrom(m: Market, T: number, n = 25, noise?: () => number): SmileQuote[] {
  const F = m.S * Math.exp((m.r - m.q) * T);
  return Array.from({ length: n }, (_, i) => {
    const K = F * (0.75 + (0.45 * i) / (n - 1));
    return { K, iv: legSigma(m, K, T) + (noise ? noise() : 0), call: K >= F };
  });
}

test.describe('SSVI calibration', () => {
  test('recovers known smiles exactly from noiseless quotes', () => {
    const u = mulberry32(31);
    const bad: string[] = [];
    for (let i = 0; i < 25; i++) {
      const rho = -0.9 + 1.5 * u(), gamma = 0.45;
      const smile: Smile = { rho, eta: 0.1 + (2 / (1 + Math.abs(rho)) - 0.15) * u(), gamma };
      const m: Market = { S: 50 + 900 * u(), sigma: 0.08 + 0.6 * u(), r: 0.05 * u(), q: 0.03 * u(), smile };
      const T = 7 / 365 + 1.5 * u();
      const cal = calibrateSmile(quotesFrom(m, T), m.S, m.r, m.q, T, gamma)!;
      const ctx = JSON.stringify({ m, T, fit: { sigma: cal.sigma, smile: cal.smile, rmse: cal.rmseVolPts } });
      if (!(cal.rmseVolPts < 1e-3)) bad.push(`rmse ${cal.rmseVolPts} ${ctx}`);
      if (!(Math.abs(cal.sigma - m.sigma) < 1e-4)) bad.push(`sigma ${ctx}`);
      if (!(Math.abs(cal.smile.rho - rho) < 2e-3)) bad.push(`rho ${ctx}`);
      if (!(Math.abs(cal.smile.eta - smile.eta) < 2e-3)) bad.push(`eta ${ctx}`);
      if (!validSmile(cal.smile)) bad.push(`invalid ${ctx}`);
    }
    expect(bad.slice(0, 5)).toEqual([]);
  });

  test('with half a vol point of quote noise, the fit error matches the noise and the ATM level holds', () => {
    const u = mulberry32(32);
    const m: Market = { S: 756.48, sigma: 0.15, r: 0.045, q: 0.012, smile: { rho: -0.7, eta: 1.1, gamma: 0.45 } };
    const T = 32 / 365;
    const noise = () => (u() - 0.5) * 0.01;   // uniform ±0.5 vol pt → RMS ≈ 0.29 vol pt
    const cal = calibrateSmile(quotesFrom(m, T, 60, noise), m.S, m.r, m.q, T)!;
    expect(cal.rmseVolPts).toBeGreaterThan(0.15);
    expect(cal.rmseVolPts).toBeLessThan(0.35);
    expect(Math.abs(cal.sigma - m.sigma)).toBeLessThan(0.003);
    expect(cal.smile.rho).toBeLessThan(-0.5);
    expect(cal.atLimit).toBe(false);
  });

  test('a smile steeper than the arbitrage-free region is fitted on its boundary and flagged', () => {
    const T = 0.25, S = 100;
    // wings far steeper than any arbitrage-free SSVI slice: 20 vol points per 10% of moneyness
    const quotes = Array.from({ length: 21 }, (_, i) => {
      const K = 70 + 3 * i, k = Math.log(K / S);
      return { K, iv: 0.2 + 2 * Math.abs(k), call: K >= S };
    });
    const cal = calibrateSmile(quotes, S, 0, 0, T)!;
    expect(validSmile(cal.smile)).toBe(true);
    expect(cal.atLimit).toBe(true);
    expect(cal.rmseVolPts).toBeGreaterThan(0.5);
  });

  test('inside the region γ only re-expresses the slice; for steep short-dated smiles a larger γ reaches further', () => {
    const T = 0.1;
    // a mild smile: both fits are interior and give the same volatilities
    const mild: Market = { S: 200, sigma: 0.3, r: 0.02, q: 0, smile: { rho: -0.35, eta: 0.5, gamma: 0.4 } };
    const a = calibrateSmile(quotesFrom(mild, T), mild.S, mild.r, mild.q, T, 0.4)!;
    const b = calibrateSmile(quotesFrom(mild, T), mild.S, mild.r, mild.q, T, 0.25)!;
    expect(a.atLimit || b.atLimit).toBe(false);
    for (let i = 0; i < a.points.length; i++) expect(Math.abs(a.points[i].ivModel - b.points[i].ivModel)).toBeLessThan(2e-5);
    expect(b.smile.gamma).toBe(0.25);
    // a steep one: φ = η·θ^−γ·(1+θ)^(γ−1) with η capped, so at small θ a small γ cannot reach it
    const steep: Market = { ...mild, smile: { rho: -0.35, eta: 1.2, gamma: 0.4 } };
    const low = calibrateSmile(quotesFrom(steep, T), steep.S, steep.r, steep.q, T, 0.25)!;
    const high = calibrateSmile(quotesFrom(steep, T), steep.S, steep.r, steep.q, T, 0.5)!;
    expect(low.atLimit).toBe(true);
    expect(high.atLimit).toBe(false);
    expect(high.rmseVolPts).toBeLessThan(low.rmseVolPts);
  });

  test('too few quotes or no time to expiry gives no calibration', () => {
    const m: Market = { S: 100, sigma: 0.2, r: 0, q: 0, smile: { rho: -0.5, eta: 1, gamma: 0.45 } };
    expect(calibrateSmile(quotesFrom(m, 0.1, MIN_QUOTES - 1), 100, 0, 0, 0.1)).toBeNull();
    expect(calibrateSmile(quotesFrom(m, 0.1), 100, 0, 0, 0)).toBeNull();
    expect(calibrateSmile([], 100, 0, 0, 0.1)).toBeNull();
  });

  test('quote selection: out of the money, a usable IV and a live quote, one per strike', () => {
    const o = (type: 'call' | 'put', strike: number, iv: number | undefined, bid = 1, last = 1): LiveChainOption =>
      ({ symbol: `${type}${strike}`, type, strike, bid, ask: bid + 0.1, last, openInterest: 10, iv });
    const chain = [
      o('put', 90, 0.25), o('call', 90, 0.21),            // below the forward: the put
      o('put', 110, 0.19), o('call', 110, 0.17),          // above: the call
      o('call', 120, undefined), o('call', 125, 0),       // no usable IV
      o('put', 80, 0.3, 0, 0),                            // no quote
      o('call', 130, 0.9),                                // far outside the ATM band
      o('put', 70, 0.34, 0, 0.05),                        // last trade only: kept
    ];
    expect(otmQuotes(chain, 100, 0.2)).toEqual([
      { K: 70, iv: 0.34, call: false }, { K: 90, iv: 0.25, call: false }, { K: 110, iv: 0.17, call: true },
    ]);
    expect(otmQuotes(chain, 100).map(q => q.K)).toEqual([70, 90, 110, 130]);   // without an ATM band
  });

  test('years to expiry counts to 4 pm New York and never less than a day', () => {
    const now = Date.parse('2026-09-14T15:00:00Z');
    expect(yearsToExpiry('2026-10-16', now)).toBeCloseTo(32 / 365, 12);
    expect(yearsToExpiry('2026-09-14', now)).toBeCloseTo(1 / 365, 12);
    expect(yearsToExpiry('2026-09-10', now)).toBeCloseTo(1 / 365, 12);
  });
});

/** One slice per maturity (days), quoted by the app's own surface. */
const surfaceFrom = (m: Market, days: number[], n = 25, noise?: () => number): SurfaceSliceInput[] =>
  days.map(d => ({ expiry: `${d}d`, T: d / 365, quotes: quotesFrom(m, d / 365, n, noise) }));

const DAYS = [9, 23, 37, 65, 100, 190, 380];

test.describe('SSVI surface calibration', () => {
  test('recovers known surfaces — smile and ATM term structure — from noiseless quotes at seven expiries', () => {
    const u = mulberry32(41);
    const bad: string[] = [];
    let ms = 0;
    for (let i = 0; i < 8; i++) {
      const rho = -0.85 + 1.2 * u(), gamma = 0.2 + 0.3 * u();
      const smile: Smile = { rho, eta: 0.2 + (2 / (1 + Math.abs(rho)) - 0.3) * u(), gamma };
      const m: Market = { S: 50 + 900 * u(), sigma: 0.1 + 0.4 * u(), r: 0.05 * u(), q: 0.02 * u(), smile,
                          term: { kind: 'curve', ratio: 0.6 + 1.2 * u(), halfLife: 0.1 + u() } };
      const t0 = performance.now();
      const cal = calibrateSurface(surfaceFrom(m, DAYS), m.S, m.r, m.q)!;
      ms += performance.now() - t0;
      const ctx = JSON.stringify({ m, fit: { sigma: cal.sigma, smile: cal.smile, rmse: cal.rmseVolPts } });
      if (!(cal.rmseVolPts < 2e-3)) bad.push(`rmse ${cal.rmseVolPts} ${ctx}`);
      // σ is the 30-day vol of the fitted pillars: total variance interpolated between the 23- and 37-day expiries
      const truePillars = fittedTerm(DAYS.map(d => d / 365), DAYS.map(d => atmVariance(m, d / 365)))!;
      if (!(Math.abs(cal.sigma - truePillars.sigma) < 1e-4)) bad.push(`sigma ${cal.sigma} vs ${truePillars.sigma} ${ctx}`);
      for (const s of cal.slices) if (!(Math.abs(s.atmVol - atmVol(m, s.T)) < 1e-4)) bad.push(`atm ${s.expiry} ${s.atmVol} vs ${atmVol(m, s.T)} ${ctx}`);
      if (!(Math.abs(cal.smile.rho - rho) < 5e-3)) bad.push(`rho ${ctx}`);
      if (!validSmile(cal.smile) || !cal.term || !validTerm(cal.term) || cal.pooled) bad.push(`invalid ${ctx}`);
    }
    console.log(`  surface fit: 7 expiries × 25 quotes in ${(ms / 8).toFixed(0)} ms on average`);
    expect(bad.slice(0, 5)).toEqual([]);
  });

  test('with half a vol point of quote noise the fit error matches the noise and each expiry’s ATM level holds', () => {
    const u = mulberry32(42);
    const m: Market = { S: 756.48, sigma: 0.14, r: 0.045, q: 0.012, smile: { rho: -0.7, eta: 1.1, gamma: 0.4 },
                        term: { kind: 'curve', ratio: 0.7, halfLife: 0.5 } };
    const noise = () => (u() - 0.5) * 0.01;   // uniform ±0.5 vol pt → RMS ≈ 0.29 vol pt
    const cal = calibrateSurface(surfaceFrom(m, DAYS, 60, noise), m.S, m.r, m.q)!;
    expect(cal.rmseVolPts).toBeGreaterThan(0.2);
    expect(cal.rmseVolPts).toBeLessThan(0.35);
    for (const s of cal.slices) expect(Math.abs(s.atmVol - atmVol(m, s.T))).toBeLessThan(0.003);
    expect(cal.smile.rho).toBeLessThan(-0.5);
    expect(cal.quotes).toBe(DAYS.length * 60);
  });

  test('the report is exactly what the app prices: model vols equal legSigma on the fitted market', () => {
    const m: Market = { S: 200, sigma: 0.3, r: 0.03, q: 0, smile: { rho: -0.4, eta: 0.8, gamma: 0.35 },
                        term: { kind: 'curve', ratio: 1.4, halfLife: 0.3 } };
    const cal = calibrateSurface(surfaceFrom(m, [5, 30, 90, 400]), m.S, m.r, m.q)!;
    const fitted: Market = { S: m.S, sigma: cal.sigma, r: m.r, q: m.q, smile: cal.smile, term: cal.term };
    for (const s of cal.slices) {
      expect(s.atmVol).toBe(atmVol(fitted, s.T));
      for (const p of s.points) expect(p.ivModel).toBe(legSigma(fitted, p.K, s.T));
      expect(s.marketAtmVol).toBeCloseTo(atmVol(m, s.T), 3);   // quotes straddle the forward: interpolated market ATM vol
    }
  });

  test('calendar arbitrage in the quotes is pooled away: the fitted surface has none', () => {
    // the 40-day expiry is quoted at 15% and the 30-day at 22%: total variance falls from 30 to 40 days
    const flat = (sigma: number): Market => ({ S: 100, sigma, r: 0, q: 0, smile: { rho: -0.5, eta: 1, gamma: 0.45 } });
    const slices = [...surfaceFrom(flat(0.2), [10]), ...surfaceFrom(flat(0.22), [30]), ...surfaceFrom(flat(0.15), [40]),
                    ...surfaceFrom(flat(0.2), [120])];
    const cal = calibrateSurface(slices, 100, 0, 0)!;
    expect(cal.pooled).toBe(true);
    expect(validTerm(cal.term!)).toBe(true);
    const fitted: Market = { S: 100, sigma: cal.sigma, r: 0, q: 0, smile: cal.smile, term: cal.term };
    const theta = cal.slices.map(s => atmVariance(fitted, s.T));
    expect(theta[2]).toBe(theta[1]);                                    // the two pooled expiries share one θ
    for (let i = 1; i < theta.length; i++) expect(theta[i]).toBeGreaterThanOrEqual(theta[i - 1]);
    for (let j = 0; j <= 60; j++) {
      const K = 100 * Math.exp(-0.6 + j * 0.02);
      const c = (d: number) => bsPrice(true, 100, K, d / 365, legSigma(fitted, K, d / 365), 0, 0);
      expect(c(40) - c(30)).toBeGreaterThanOrEqual(-1e-9);
    }
  });

  test('one usable expiry is the single-slice fit with no term structure; none gives no calibration', () => {
    const m: Market = { S: 100, sigma: 0.25, r: 0.01, q: 0, smile: { rho: -0.3, eta: 0.9, gamma: 0.5 } };
    const slices = [...surfaceFrom(m, [45]), { expiry: 'thin', T: 90 / 365, quotes: quotesFrom(m, 90 / 365, MIN_QUOTES - 1) }];
    const cal = calibrateSurface(slices, m.S, m.r, m.q)!;
    const single = calibrateSmile(slices[0].quotes, m.S, m.r, m.q, 45 / 365, 0.5)!;
    expect(cal.term).toBeNull();
    expect(cal.slices.map(s => s.expiry)).toEqual(['45d']);
    expect(cal.sigma).toBe(single.sigma);
    expect(cal.smile).toEqual(single.smile);
    expect(calibrateSurface(slices.slice(1), m.S, m.r, m.q)).toBeNull();
    expect(calibrateSurface([], m.S, m.r, m.q)).toBeNull();
    expect(calibrateSurface(surfaceFrom(m, [45]), 0, 0, 0)).toBeNull();
  });

  test('the compute-worker task returns the same fit, timed, and null when nothing can be fitted', () => {
    const m: Market = { S: 420, sigma: 0.22, r: 0.04, q: 0.01, smile: { rho: -0.6, eta: 1, gamma: 0.4 },
                        term: { kind: 'curve', ratio: 0.6, halfLife: 0.2 } };
    const req = { slices: surfaceFrom(m, [9, 30, 120]), S: m.S, r: m.r, q: m.q };
    const res = runTask('surface', req);
    expect(res.cal).toEqual(calibrateSurface(req.slices, req.S, req.r, req.q));
    expect(res.ms).toBeGreaterThanOrEqual(0);
    expect(runTask('surface', { ...req, slices: [] }).cal).toBeNull();
  });

  test('expiry selection spreads maturities from a week to a year and a half and keeps the legs’ expiry', () => {
    const now = Date.parse('2026-09-14T15:00:00Z');
    const iso = (d: number) => new Date(now + d * 86_400_000).toISOString().slice(0, 10);
    // SPY-like listing: daily for two months, then monthlies and LEAPS out to 641 days
    const listed = [...Array.from({ length: 45 }, (_, d) => iso(d)), ...[67, 95, 123, 186, 277, 368, 494, 641].map(iso)];
    const picked = pickSurfaceExpiries(listed, '', now);
    const dte = picked.map(e => Math.round(yearsToExpiry(e, now) * 365));
    expect(dte).toEqual([7, 14, 30, 67, 95, 186, 368, 494]);
    expect([...picked].sort()).toEqual(picked);
    const withLegs = pickSurfaceExpiries(listed, iso(2), now);           // a 2-day expiry: below the usual minimum, kept anyway
    expect(withLegs).toContain(iso(2));
    expect(withLegs).toHaveLength(8);
    expect(withLegs).not.toContain(iso(7));                              // it replaced the nearest pick
    expect(pickSurfaceExpiries([iso(1), iso(3), iso(10), 'bad', iso(10)], '', now)).toEqual([iso(10)]);
    expect(pickSurfaceExpiries([], 'x', now)).toEqual([]);
  });

  test('loading a surface keeps out-of-the-money quotes per expiry and reports chains that fail', async () => {
    const now = Date.parse('2026-09-14T15:00:00Z');
    const opt = (type: 'call' | 'put', strike: number, iv: number): LiveChainOption =>
      ({ symbol: `${type}${strike}`, type, strike, bid: 1, ask: 1.1, last: 1, openInterest: 5, iv });
    const options = [opt('put', 90, 0.24), opt('call', 90, 0.2), opt('put', 100, 0.2), opt('call', 101, 0.19), opt('call', 110, 0.17), opt('call', 150, 0.9)];
    const getChain = async (symbol: string, expiration: string) => {
      if (expiration === '2026-12-18') throw new Error('proxy 502');
      return { symbol, expiration, feed: 'indicative', options };
    };
    const { slices, failed } = await loadSurfaceSlices('SPY', ['2026-10-16', '2026-12-18'], 100, 0, 0, now, getChain);
    expect(failed).toEqual(['2026-12-18']);
    expect(slices).toHaveLength(1);
    expect(slices[0].T).toBeCloseTo(32 / 365, 12);
    // forward 100: the 100 put is not out of the money, the 90 call is in the money, the 150 call is outside the ATM band
    expect(slices[0].quotes).toEqual([{ K: 90, iv: 0.24, call: false }, { K: 101, iv: 0.19, call: true }, { K: 110, iv: 0.17, call: true }]);
    expect(atmReferenceIv(options, 100)).toBe(0.19);
    expect(atmReferenceIv(options, 100.4)).toBe(0.2);
  });
});
